### ISSUE TITLE
Is it compatible with Vuejs 2?

### ISSUE THREAD

**Issue by bissolli** [ElemeFE/vue-msgbox#17]
I am having the following issue! I think it's version issue no?

```
Uncaught (in promise) TypeError: i.$appendTo is not a function
    at g (eval at 741 (0.e114a86….hot-update.js:13), <anonymous>:1:1921)
    at eval (eval at 741 (0.e114a86….hot-update.js:13), <anonymous>:1:2286)
    at _ (eval at 741 (0.e114a86….hot-update.js:13), <anonymous>:1:2187)
    at VueComponent.askToDelete (eval at 458 (0.8f8fd8b….hot-update.js:6), <anonymous>:53:37)
    at Proxy.boundFn (eval at <anonymous> (app.js:610), <anonymous>:126:14)
    at Object.click (eval at 666 (0.36270e0….hot-update.js:6), <anonymous>:115:13)
    at HTMLSpanElement.eval (eval at <anonymous> (app.js:610), <anonymous>:2170:16)
```

**Comment by amanpatel** [comment]
Same kind of issue.

**Comment by dodanex** [comment]
I will like to use this awesome tool but first I'll wait for VUE 2 compatibility

**Comment by distortia** [comment]
Looks like you guys are using the 1.x version of this. 
Check out https://github.com/ElemeFE/vue-msgbox/issues/14

It says to install `vue-msgbox@2.0.1` 

Its working with using vue 2.0.

**Comment by jamestowers** [comment]
I'm getting an error using `vue-msgbox@2.0.1` with Vue 2.1.10:

```
_h is not defined
```

Seems to be related to a change in a newer version of Vue? Similar problem to here: https://github.com/vue-play/vue-play/issues/40

**Comment by jamestowers** [comment]
A simple rebuild fixes that issue. 

For those wanting a quick fix, you can download the repo, run `npm install` then `webpack -p` and copy over and replace `lib/vue-msgbox.js` in your project's node_modules

**Comment by xxRockOnxx** [comment]
Is this still actively maintained? Would like to make a PR with the new `lib/vue-msgbox.js` just like what @jamestowers said.

**EDIT** whoops, I thought lib was included here in Github.

**Comment by parox2014** [comment]
散了吧，都没人维护了

**Comment by muyaedward** [comment]
Is this issue fixed?
`bids.js:sourcemap:63755 Uncaught (in promise) TypeError: i.$appendTo is not a function
    at g (bids.js:sourcemap:63755)
    at bids.js:sourcemap:63755
    at new Promise (<anonymous>)
    at _ (bids.js:sourcemap:63755)
    at Function.Vue.use (bids.js:sourcemap:10280)
    at Object.map../af (bids.js:sourcemap:59402)
    at __webpack_require__ (bids.js:sourcemap:20)
    at Object.<anonymous> (bids.js:sourcemap:59218)
    at __webpack_require__ (bids.js:sourcemap:20)
    at Object.disposed (bids.js:sourcemap:59201)`
